server:
  port: 8081



spring:
  application:
    name: client01
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lecture_training_test1?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

file:
  name: zhangjiawen

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka


